// Full purchasable options / SKUs, imported from the HealthServe finance master.
// One entry per buyable option. price = live Offer (AED); mrp = strike-through.
export interface ServiceOption { name: string; label?: string; price: number; mrp?: number; addon?: boolean }
export const serviceOptions: Record<string, ServiceOption[]> = {
  "flu-vaccination": [
    { name:"Flu Vaccine At Home", label:"Nurse Visit - Lasting upto 1 hour", price:299, mrp:349 },
  ],
  "im-shots": [
    { name:"Injection service At Home (SC, im, iv). With prescription only", label:"Nurse Visit - Lasting upto 1 hour", price:149, mrp:249 },
    { name:"Vitamin D Injection At Home", label:"Nurse Visit - Lasting upto 1 hour", price:299, mrp:399 },
    { name:"Vitamin B12 Injection At Home", label:"Nurse Visit - Lasting upto 1 hour", price:349, mrp:349 },
  ],
  "iv-therapy": [
    { name:"Elara Skin Glow Drip - Glutathione 600 mg", label:"1 session(s)", price:399, mrp:479 },
    { name:"Glowing and radiant skin IV Drip", label:"1 session(s)", price:749, mrp:969 },
    { name:"Healthy Heart IV Drip or Cardio Support IV Drip", label:"1 session(s)", price:749, mrp:969 },
    { name:"Healthy GUT IV Drip or GUT Support IV Therapy", label:"1 session(s)", price:749, mrp:969 },
    { name:"Healthy Liver IV Drip", label:"1 session(s)", price:749, mrp:969 },
    { name:"Memory Boost IV Drip", label:"1 session(s)", price:749, mrp:969 },
    { name:"Female balance IV Drip", label:"1 session(s)", price:749, mrp:969 },
    { name:"Diabetic Support IV Drip", label:"1 session(s)", price:749, mrp:969 },
    { name:"Multi Vitamins IV drip", label:"1 session(s)", price:749, mrp:969 },
    { name:"Immunity Booster IV drip", label:"1 session(s)", price:749, mrp:969 },
    { name:"Antistress and Antioxidant IV Drip", label:"1 session(s)", price:749, mrp:969 },
    { name:"Energy booster and fitness support IV Drip", label:"1 session(s)", price:749, mrp:969 },
    { name:"Elara Skin Glow Drip - Glutathione 600 mg", label:"2 session(s)", price:779, mrp:929 },
    { name:"Hair Regeneration IV Drip", label:"1 session(s)", price:800, mrp:1000 },
    { name:"Blood and Iron Boost IV Drip (others same)", label:"1 session(s)", price:800, mrp:1000 },
    { name:"Anti-aging IV Drip", label:"1 session(s)", price:1100, mrp:1500 },
    { name:"Comprehensive Anti-Aging IV Drip", label:"1 session(s)", price:1100, mrp:1500 },
    { name:"Elara Skin Glow Drip - Glutathione 600 mg", label:"4 session(s)", price:1119, mrp:1399 },
    { name:"Glowing and radiant skin IV Drip", label:"2 session(s)", price:1478, mrp:1920 },
    { name:"Healthy Heart IV Drip or Cardio Support IV Drip", label:"2 session(s)", price:1478, mrp:1920 },
    { name:"Healthy GUT IV Drip or GUT Support IV Therapy", label:"2 session(s)", price:1478, mrp:1920 },
    { name:"Healthy Liver IV Drip", label:"2 session(s)", price:1478, mrp:1920 },
    { name:"Memory Boost IV Drip", label:"2 session(s)", price:1478, mrp:1920 },
    { name:"Female balance IV Drip", label:"2 session(s)", price:1478, mrp:1920 },
    { name:"Diabetic Support IV Drip", label:"2 session(s)", price:1478, mrp:1920 },
    { name:"Multi Vitamins IV drip", label:"2 session(s)", price:1478, mrp:1920 },
    { name:"Immunity Booster IV drip", label:"2 session(s)", price:1478, mrp:1920 },
    { name:"Antistress and Antioxidant IV Drip", label:"2 session(s)", price:1478, mrp:1920 },
    { name:"Energy booster and fitness support IV Drip", label:"2 session(s)", price:1478, mrp:1920 },
    { name:"Hair Regeneration IV Drip", label:"2 session(s)", price:1578, mrp:1980 },
    { name:"Blood and Iron Boost IV Drip (others same)", label:"2 session(s)", price:1578, mrp:1980 },
    { name:"Elara Skin Glow Drip - Glutathione 600 mg", label:"6 session(s)", price:1619, mrp:1999 },
    { name:"Anti-aging IV Drip", label:"2 session(s)", price:2150, mrp:2900 },
    { name:"Comprehensive Anti-Aging IV Drip", label:"2 session(s)", price:2150, mrp:2900 },
    { name:"Glowing and radiant skin IV Drip", label:"4 session(s)", price:2916, mrp:3796 },
    { name:"Healthy Heart IV Drip or Cardio Support IV Drip", label:"4 session(s)", price:2916, mrp:3796 },
    { name:"Healthy GUT IV Drip or GUT Support IV Therapy", label:"4 session(s)", price:2916, mrp:3796 },
    { name:"Healthy Liver IV Drip", label:"4 session(s)", price:2916, mrp:3796 },
    { name:"Memory Boost IV Drip", label:"4 session(s)", price:2916, mrp:3796 },
    { name:"Female balance IV Drip", label:"4 session(s)", price:2916, mrp:3796 },
    { name:"Diabetic Support IV Drip", label:"4 session(s)", price:2916, mrp:3796 },
    { name:"Multi Vitamins IV drip", label:"4 session(s)", price:2916, mrp:3796 },
    { name:"Immunity Booster IV drip", label:"4 session(s)", price:2916, mrp:3796 },
    { name:"Antistress and Antioxidant IV Drip", label:"4 session(s)", price:2916, mrp:3796 },
    { name:"Energy booster and fitness support IV Drip", label:"4 session(s)", price:2916, mrp:3796 },
    { name:"Hair Regeneration IV Drip", label:"4 session(s)", price:3116, mrp:3920 },
    { name:"Blood and Iron Boost IV Drip (others same)", label:"4 session(s)", price:3116, mrp:3920 },
    { name:"EDTA Chelation IV Drip (minimum 5 sessions)", label:"5 s session(s)", price:3999, mrp:4819 },
    { name:"Heavy Metal Detox IV Drip (minimum 5 sessions)", label:"5 s session(s)", price:3999, mrp:4819 },
    { name:"Anti-aging IV Drip", label:"4 session(s)", price:4200, mrp:5600 },
    { name:"Comprehensive Anti-Aging IV Drip", label:"4 session(s)", price:4200, mrp:5600 },
    { name:"Glowing and radiant skin IV Drip", label:"6 session(s)", price:4314, mrp:5634 },
    { name:"Healthy Heart IV Drip or Cardio Support IV Drip", label:"6 session(s)", price:4314, mrp:5634 },
    { name:"Healthy GUT IV Drip or GUT Support IV Therapy", label:"6 session(s)", price:4314, mrp:5634 },
    { name:"Healthy Liver IV Drip", label:"6 session(s)", price:4314, mrp:5634 },
    { name:"Memory Boost IV Drip", label:"6 session(s)", price:4314, mrp:5634 },
    { name:"Female balance IV Drip", label:"6 session(s)", price:4314, mrp:5634 },
    { name:"Diabetic Support IV Drip", label:"6 session(s)", price:4314, mrp:5634 },
    { name:"Multi Vitamins IV drip", label:"6 session(s)", price:4314, mrp:5634 },
    { name:"Immunity Booster IV drip", label:"6 session(s)", price:4314, mrp:5634 },
    { name:"Antistress and Antioxidant IV Drip", label:"6 session(s)", price:4314, mrp:5634 },
    { name:"Energy booster and fitness support IV Drip", label:"6 session(s)", price:4314, mrp:5634 },
    { name:"Hair Regeneration IV Drip", label:"6 session(s)", price:4614, mrp:5820 },
    { name:"Blood and Iron Boost IV Drip (others same)", label:"6 session(s)", price:4614, mrp:5820 },
    { name:"Anti-aging IV Drip", label:"6 session(s)", price:6000, mrp:8100 },
    { name:"Comprehensive Anti-Aging IV Drip", label:"6 session(s)", price:6000, mrp:8100 },
    { name:"Men Fertility Boost IV Drip (5 sessions minimum)", label:"5 session(s)", price:6499, mrp:8319 },
    { name:"Female Fertility Boost IV Drip (5 sessions minimum)", label:"5 session(s)", price:6499, mrp:8319 },
  ],
  "nad-therapy": [
    { name:"NAD+ 100 mg Energy Boost and Anti-Aging IV Drip", label:"1 session(s)", price:449, mrp:699 },
    { name:"NAD+ 100 mg Energy Boost and Anti-Aging IV Drip", label:"2 session(s)", price:890, mrp:1358 },
    { name:"NAD+ 250 mg Energy Boost and Anti-Aging IV Drip", label:"1 session(s)", price:925, mrp:1249 },
    { name:"NAD+ 500 mg Energy Boost and Anti-Aging IV Drip", label:"1 session(s)", price:1399, mrp:1809 },
    { name:"NAD+ 100 mg Energy Boost and Anti-Aging IV Drip", label:"4 session(s)", price:1740, mrp:2716 },
    { name:"NAD+ 250 mg Energy Boost and Anti-Aging IV Drip", label:"2 session(s)", price:1799, mrp:2490 },
    { name:"NAD+ 100 mg Energy Boost and Anti-Aging IV Drip", label:"6 session(s)", price:2549, mrp:4014 },
    { name:"NAD+ 500 mg Energy Boost and Anti-Aging IV Drip", label:"2 session(s)", price:2699, mrp:3499 },
    { name:"NAD+ 250 mg Energy Boost and Anti-Aging IV Drip", label:"4 session(s)", price:3499, mrp:5000 },
    { name:"NAD+ 250 mg Energy Boost and Anti-Aging IV Drip", label:"6 session(s)", price:5099, mrp:7500 },
    { name:"NAD+ 500 mg Energy Boost and Anti-Aging IV Drip", label:"4 session(s)", price:5199, mrp:6749 },
    { name:"NAD+ 500 mg Energy Boost and Anti-Aging IV Drip", label:"6 session(s)", price:7199, mrp:8679 },
  ],
  "doctor-visit": [
    { name:"Doctor Consultation (GP Visit) – At Home", label:"Doctor Visit at Home - (9am to 9pm)", price:299, mrp:375 },
    { name:"Doctor Consultation (GP Visit) – At Home", label:"Express Doctor Visit (9pm to 9am)", price:399, mrp:500 },
  ],
  "elderly-care": [
    { name:"Nurse Visit - Elderly Geriatric Care", label:"Lasting upto 1 hour", price:149, mrp:249 },
    { name:"Nurse Visit - Elderly Geriatric Care", label:"4hr", price:449, mrp:599 },
    { name:"Nurse Visit - Elderly Geriatric Care", label:"8hr", price:749, mrp:949 },
    { name:"Nurse Visit - Elderly Geriatric Care", label:"12hr", price:899, mrp:1199 },
    { name:"Nurse Visit - Elderly Geriatric Care", label:"24hr (medical report from consumer)", price:1399, mrp:1500 },
  ],
  "home-nursing": [
    { name:"Nursing service at Home", label:"Lasting upto 1 hour", price:149, mrp:249 },
    { name:"Nursing service at Home - Lasting upto 1 hour", price:149 },
    { name:"Care Giver", label:"4hr", price:299, mrp:445 },
    { name:"Nursing service at Home", label:"4hr", price:449, mrp:599 },
    { name:"Care Giver", label:"8hr", price:499, mrp:799 },
    { name:"Care Giver", label:"12hr", price:649, mrp:1057 },
    { name:"Nursing service at Home", label:"8hr", price:749, mrp:949 },
    { name:"Nursing service at Home", label:"12hr", price:899, mrp:1199 },
    { name:"Care Giver", label:"24hr (medical report from consumer)", price:999, mrp:1410 },
    { name:"Nursing service at Home", label:"24hr (medical report from consumer)", price:1399, mrp:1500 },
  ],
  "lab-tests": [
    { name:"Kidney Function Test", price:89, mrp:125 },
    { name:"Liver Function Test", price:89, mrp:125 },
    { name:"Thyroid Function Tests", price:89, mrp:125 },
    { name:"Complete Blood Count", price:99, mrp:125 },
    { name:"Lipid (Cholesterol) Profile", price:99, mrp:125 },
    { name:"Vitamin D Test", price:149, mrp:175 },
    { name:"Complete Urine Analysis", price:149, mrp:175 },
    { name:"Pregnancy Blood Test", price:149, mrp:175 },
    { name:"Essential Male Hormone Profile", price:169, mrp:200 },
    { name:"Prostate Screening Profile", price:189, mrp:225 },
    { name:"Essential Female Hormone Profile", price:189, mrp:225 },
    { name:"UTI (Urinary Tract Infection)", price:239, mrp:275 },
    { name:"Dengue Test (NS 1 Antigen) - Fast Track", price:239, mrp:275 },
    { name:"Diabetes Profile", price:239, mrp:275 },
    { name:"Homa Insulin Resistance Index", price:249 },
    { name:"Urine Culture & Sensitivity", price:250, mrp:125 },
    { name:"Inhalant Allergy Test", price:339, mrp:400 },
    { name:"Food Allergy Test", price:339, mrp:400 },
    { name:"Basic STD Test", price:339, mrp:400 },
    { name:"Thyroid Antibodies", price:339, mrp:400 },
    { name:"Pediatric Wellness Profile", price:349, mrp:450 },
    { name:"Teenage Wellness Profile", price:349, mrp:450 },
    { name:"Essential Vitamins & Minerals Profile", price:379, mrp:450 },
    { name:"Women's Basic Weight Wellness Check (Essential Female Weight Loss Blood Profile)", price:379, mrp:450 },
    { name:"Men's Basic Weight Wellness Check (Essential Male Weight Loss Blood Profile)", price:379, mrp:450 },
    { name:"Hair Loss Blood Profile", price:389, mrp:450 },
    { name:"Cancer Screening - Female", price:399, mrp:450 },
    { name:"Cancer Screening - Male", price:399, mrp:450 },
    { name:"Flu Profile", price:429, mrp:525 },
    { name:"Pediatric Flu Profile", price:429, mrp:525 },
    { name:"Advanced Fever Profile", price:429, mrp:525 },
    { name:"Comprehensive STD Test", price:429, mrp:525 },
    { name:"Energy Booster Blood Profile", price:429, mrp:525 },
    { name:"Electrolyte Profile", price:439, mrp:525 },
    { name:"Comprehensive Female Hormone Profile", price:469, mrp:586 },
    { name:"Comprehensive Male Hormone Profile", price:479, mrp:575 },
    { name:"Fitness Profile", price:489, mrp:575 },
    { name:"Polycystic Ovarian Syndrome (PCOS) Profile", price:579, mrp:700 },
    { name:"Comprehensive Blood Profile - Male", price:619, mrp:750 },
    { name:"Comprehensive Blood Profile - Female", price:619, mrp:750 },
    { name:"Men's Complete Weight Wellness Check (Ultimate Male Weight Loss Blood Profile)", price:639, mrp:750 },
    { name:"Women's Complete Weight Wellness Check (Ultimate Female Weight Loss Blood Profile)", price:639, mrp:750 },
    { name:"Antenatal (Pregnancy) Profile", price:649 },
    { name:"Essential Full Body Profile", price:719, mrp:850 },
    { name:"Sedentary Lifestyle Impact Analysis Profile", price:749 },
    { name:"Healthy Heart Basic Profile", price:749 },
    { name:"Smoking Impact Analysis Profile", price:749 },
    { name:"Alcohol Impact Analysis Profile", price:749 },
    { name:"Arthritis Screening Profile (Joints Profile)", price:749 },
    { name:"Saliva Stress Test", price:749, mrp:1275 },
    { name:"Digestive Health Profile", price:769, mrp:925 },
    { name:"Perimenopause Profile", price:769, mrp:925 },
    { name:"Comprehensive Vitamin Profile", price:799, mrp:575 },
    { name:"Skin Health Blood Profile", price:859, mrp:1025 },
    { name:"Premarital Health Screening", price:949, mrp:1150 },
    { name:"Comprehensive Yearly Full Body Profile - Male 40+", price:999 },
    { name:"Comprehensive Yearly Full Body Profile - Female 40+", price:999 },
    { name:"Healthy Heart Advanced Profile", price:999 },
    { name:"Comprehensive Bone Profile", price:999 },
    { name:"Comprehensive Post Delivery Mother Profile", price:999 },
    { name:"Comprehensive Blood Profile - Couple", price:1199, mrp:1525 },
    { name:"Comprehensive Blood Profile - Parents", price:1199, mrp:1525 },
    { name:"Comprehensive Full Body Profile - Couple", price:1199 },
    { name:"Comprehensive Full Body Profile - Parents", price:1199 },
    { name:"Food Intolerance Test - Standard", price:1199, mrp:800 },
    { name:"Comprehensive Full Body Profile", price:1249, mrp:1750 },
    { name:"NIPT Basic - Non Invasive Prenatal Test", price:1249, mrp:1500 },
    { name:"Comprehensive Allergy Test", price:1500, mrp:800 },
    { name:"NIPT Advance - Non-Invasive Prenatal Testing", price:1729, mrp:2075 },
    { name:"Heavy Metal Profile", price:1939, mrp:2300 },
    { name:"Comprehensive Stool Analysis", price:2399, mrp:2875 },
    { name:"ABSOLUTE EOSINOPHIL COUNT", price:100, addon:true },
    { name:"ABSOLUTE LYMPHOCYTE COUNT", price:100, addon:true },
    { name:"ABSOLUTE NEUTROPHIL COUNT", price:100, addon:true },
    { name:"ACID PHOSPHATASE, TOTAL", price:100, addon:true },
    { name:"AFB STAIN", price:100, addon:true },
    { name:"ALBUMIN", price:100, addon:true },
    { name:"ALKALINE PHOSPHATASE (ALP)", price:100, addon:true },
    { name:"AMYLASE", price:100, addon:true },
    { name:"ANTI STREPTOLYSIN-O (ASO) TITRE", price:100, addon:true },
    { name:"APOLIPOPROTEINS A1 & B", price:100, addon:true },
    { name:"BICARBONATE", price:100, addon:true },
    { name:"BILE SALTS & PIGMENTS, URINE", price:100, addon:true },
    { name:"BILIRUBIN, DIRECT", price:100, addon:true },
    { name:"BILIRUBIN, TOTAL", price:100, addon:true },
    { name:"BLOOD GROUP, ABO & RH", price:100, addon:true },
    { name:"BUN (UREA), URINE", price:100, addon:true },
    { name:"BUN: BLOOD UREA NITROGEN", price:100, addon:true },
    { name:"CALCIUM", price:100, addon:true },
    { name:"CALCIUM, RANDOM URINE", price:100, addon:true },
    { name:"CHOLESTEROL, TOTAL", price:100, addon:true },
    { name:"COMPLETE BLOOD COUNT; CBC", price:100, addon:true },
    { name:"COOMBS TEST, DIRECT", price:100, addon:true },
    { name:"COOMBS TEST, INDIRECT", price:100, addon:true },
    { name:"CORTISOL, MORNING SAMPLE", price:100, addon:true },
    { name:"CPK- MB", price:100, addon:true },
    { name:"CPK; CREATINE KINASE", price:100, addon:true },
    { name:"C-REACTIVE PROTEIN; CRP", price:100, addon:true },
    { name:"CREATININE", price:100, addon:true },
    { name:"CULTURE AEROBIC, NASAL SWAB", price:100, addon:true },
    { name:"CA 125; OVARIAN CANCER MARKER", price:150, addon:true },
    { name:"CA 15.3: BREAST CANCER MARKER", price:150, addon:true },
    { name:"CA 19.9: PANCREATIC CANCER MARKER", price:150, addon:true },
    { name:"17-HYDROXYPROGESTERONE (17-OHP)", price:200, addon:true },
    { name:"ACTH", price:200, addon:true },
    { name:"AFP (ALPHA FETOPROTEIN), MATERNAL", price:200, addon:true },
    { name:"ALCOHOL (ETHANOL), URINE", price:200, addon:true },
    { name:"ALDOSTERONE", price:200, addon:true },
    { name:"ANGIOTENSIN CONVERTING ENZYME; ACE", price:200, addon:true },
    { name:"ANTI CYCLIC CITRULLINATED PEPTIDE ; ANTI CCP", price:200, addon:true },
    { name:"ANTI NUCLEAR ANTIBODY (LATEX)", price:200, addon:true },
    { name:"ANTI SPERM ANTIBODY", price:200, addon:true },
    { name:"ANTI THYROGLOBULIN ANTIBODY; ANTI TG", price:200, addon:true },
    { name:"ANTI THYROID PEROXIDASE ANTIBODY; ANTI TPO", price:200, addon:true },
    { name:"ASCA (ANTI SACCHAROMYCES CEREVISIAE ANTIBODY), IGA", price:200, addon:true },
    { name:"ASCA (ANTI SACCHAROMYCES CEREVISIAE ANTIBODY), IGG", price:200, addon:true },
    { name:"BENCE JONES PROTEIN, URINE, QUALITATIVE", price:200, addon:true },
    { name:"BRUCELLA ANTIBODY, IGG", price:200, addon:true },
    { name:"BRUCELLA ANTIBODY, IGM", price:200, addon:true },
    { name:"CARBAMAZEPINE", price:200, addon:true },
    { name:"CARDIOLIPIN ANTIBODY, IGA", price:200, addon:true },
    { name:"CARDIOLIPIN ANTIBODY, IGG", price:200, addon:true },
    { name:"CARDIOLIPIN ANTIBODY, IGM", price:200, addon:true },
    { name:"CEA; CARCINOEMBRYONIC ANTIGEN", price:200, addon:true },
    { name:"CERULOPLASMIN", price:200, addon:true },
    { name:"CHLAMYDIA ANTIGEN", price:200, addon:true },
    { name:"CHLAMYDIA TRACHOMATIS, IGG", price:200, addon:true },
    { name:"CHLAMYDIA TRACHOMATIS, IGM", price:200, addon:true },
    { name:"CHLORIDE", price:200, addon:true },
    { name:"COMPLEMENT, C3", price:200, addon:true },
    { name:"COMPLEMENT, C4", price:200, addon:true },
    { name:"C-PEPTIDE, FASTING", price:200, addon:true },
    { name:"C-REACTIVE PROTEIN, CARDIO; HS CRP", price:200, addon:true },
    { name:"CULTURE AEROBIC, URETHRAL SWAB", price:200, addon:true },
    { name:"CULTURE AEROBIC, PUS", price:200, addon:true },
    { name:"ACETONE", price:300, addon:true },
    { name:"ALPHA 1 ANTITRYPSIN QUANTITATION: AAT", price:300, addon:true },
    { name:"ANCA (ANTINEUTROPHIL CYTOPLASMIC ANTIBODIES)", price:300, addon:true },
    { name:"ANDROSTENEDIONE", price:300, addon:true },
    { name:"APOLIPOPROTEIN A1, URINE", price:300, addon:true },
    { name:"BILE ACIDS TOTAL", price:300, addon:true },
    { name:"CA 72.4: GASTRIC CANCER MARKER", price:300, addon:true },
    { name:"CALCITONIN", price:300, addon:true },
    { name:"CERVICAL SCREEN", price:300, addon:true },
    { name:"ANCA-PR 3 (SERIN PROTEINASE 3 ANTIBODIES), CORRESPONDS WITH C-ANCA", price:400, addon:true },
    { name:"ANDROGEN INDEX", price:400, addon:true },
    { name:"ANTI MULLERIAN HORMONE; AMH", price:400, addon:true },
    { name:"CA CYFRA 21-1: LUNG CANCER MARKER", price:400, addon:true },
    { name:"CULTURE AEROBIC, BLOOD RAPID", price:400, addon:true },
    { name:"ASCA (ANTI SACCHAROMYCES CEREVISIAE ANTIBODY), IGM", price:500, addon:true },
    { name:"CANDIDA ALBICANS ABS, IGA", price:600, addon:true },
    { name:"CANDIDA ALBICANS ABS, IGG", price:600, addon:true },
    { name:"CANDIDA ALBICANS ABS, IGM", price:600, addon:true },
    { name:"CATECHOLAMINES, PLASMA", price:600, addon:true },
    { name:"CHLAMYDIA TRACHOMATIS, IGA", price:600, addon:true },
    { name:"CLOSTRIDIUM DIFFICILE TOXIN", price:600, addon:true },
    { name:"ANTI DIURETIC HORMONE (ADH), VASOPRESSIN, PLASMA", price:900, addon:true },
    { name:"CHROMOGRANIN A; CGA", price:1000, addon:true },
  ],
  "newborn-child-care": [
    { name:"Nurse Visit - Newborn Baby care", label:"Lasting upto 1 hour", price:149, mrp:249 },
    { name:"Nurse Visit - Newborn Baby care", label:"4hr", price:449, mrp:599 },
    { name:"Nurse Visit - Newborn Baby care", label:"8hr", price:749, mrp:949 },
    { name:"Nurse Visit - Newborn Baby care", label:"12hr", price:899, mrp:1199 },
    { name:"Nurse Visit - Newborn Baby care", label:"24hr (medical report from consumer)", price:1399, mrp:1500 },
  ],
  "physiotherapy": [
    { name:"Physiotherapy Assessment (on taking 6 sessions, assessment is free)", price:95, mrp:105 },
    { name:"Physiotherapy Session", label:"1 session", price:289, mrp:349 },
    { name:"Sports Injury Physiotherapy", label:"1 session", price:289, mrp:349 },
    { name:"Child Physiotherapy", label:"1 session", price:289, mrp:349 },
    { name:"Neurological Physiotherapy", label:"1 session", price:289, mrp:349 },
    { name:"Stroke Physiotherapy", label:"1 session", price:289, mrp:349 },
    { name:"Bone and Joint Physiotherapy", label:"1 session", price:289, mrp:349 },
    { name:"Back and neck pain Physiotherapy", label:"1 session", price:289, mrp:349 },
    { name:"Rehabilitation Physiotherapy", label:"1 session", price:289, mrp:349 },
    { name:"Physiotherapy for elderly", label:"1 session", price:289, mrp:349 },
    { name:"Post Operative Physiotherapy", label:"1 session", price:289, mrp:349 },
    { name:"Maternity Care Physiotherapy", label:"1 session", price:289, mrp:349 },
    { name:"Chest Physiotherapy", label:"1 session", price:289, mrp:349 },
    { name:"Pain management Physiotherapy", label:"1 session", price:289, mrp:349 },
    { name:"Dry Needling Therapy", label:"1 session", price:375, mrp:469 },
    { name:"Dry Cupping Therapy", label:"1 session", price:375, mrp:469 },
    { name:"Physiotherapy Session", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Sports Injury Physiotherapy", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Child Physiotherapy", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Neurological Physiotherapy", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Stroke Physiotherapy", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Bone and Joint Physiotherapy", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Back and neck pain Physiotherapy", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Rehabilitation Physiotherapy", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Physiotherapy for elderly", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Post Operative Physiotherapy", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Maternity Care Physiotherapy", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Chest Physiotherapy", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Pain management Physiotherapy", label:"3 sessions (10% discount)", price:799, mrp:999 },
    { name:"Dry Needling Therapy", label:"3 sessions (10% discount)", price:1049, mrp:1311 },
    { name:"Dry Cupping Therapy", label:"3 sessions (10% discount)", price:1049, mrp:1311 },
    { name:"Physiotherapy Session", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Sports Injury Physiotherapy", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Child Physiotherapy", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Neurological Physiotherapy", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Stroke Physiotherapy", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Bone and Joint Physiotherapy", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Back and neck pain Physiotherapy", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Rehabilitation Physiotherapy", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Physiotherapy for elderly", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Post Operative Physiotherapy", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Maternity Care Physiotherapy", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Chest Physiotherapy", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Pain management Physiotherapy", label:"6 sessions (15% discount)", price:1449, mrp:1819 },
    { name:"Dry Needling Therapy", label:"6 sessions (15% discount)", price:1949, mrp:2436 },
    { name:"Dry Cupping Therapy", label:"6 sessions (15% discount)", price:1949, mrp:2436 },
    { name:"Physiotherapy Session", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Sports Injury Physiotherapy", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Child Physiotherapy", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Neurological Physiotherapy", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Stroke Physiotherapy", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Bone and Joint Physiotherapy", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Back and neck pain Physiotherapy", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Rehabilitation Physiotherapy", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Physiotherapy for elderly", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Post Operative Physiotherapy", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Maternity Care Physiotherapy", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Chest Physiotherapy", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Pain management Physiotherapy", label:"12 sessions (15% discount)", price:2549, mrp:3186 },
    { name:"Dry Needling Therapy", label:"12 sessions (15% discount)", price:3599, mrp:4499 },
    { name:"Dry Cupping Therapy", label:"12 sessions (15% discount)", price:3599, mrp:4499 },
  ],
  "teleconsultation": [
    { name:"Online Doctor Consultation (General Practitioner)", label:"Online", price:149, mrp:200 },
    { name:"Online Doctor Consultation (General Practitioner)", price:149 },
  ],
};
